FROM golang:1.27 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o application-service ./cmd

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/application-service .

EXPOSE 8084

CMD ["./application-service"]