FROM golang:1.27 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o gateway .

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/gateway .

EXPOSE 8079

CMD ["./gateway"]