FROM golang:1.27 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o company-service ./cmd

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/company-service .

EXPOSE 8082

CMD ["./company-service"]