FROM golang:1.27 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o job-service ./cmd

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/job-service .

EXPOSE 8083

CMD ["./job-service"]